baseURL = "https://pedantic-meninsky-a943cd.netlify.com/"
languageCode = "kr-ko"
DefaultContentLanguage = "kr"
title = "KNLabs"
theme = "hello"
disqusShortname = "robertchoi-disqus-com"
paginate = 5

[author]
    name = "robert"
    email = "robert@knlabs.kr"

[params]
    description = "KNLabs 오픈연구소 홈페이지입니다."



