baseURL = "https://www.knlabs.com/"
languageCode = "kr-ko"
DefaultContentLanguage = "kr"
title = "KNLabs Site"
theme = "hello"
disqusShortname = "robertchoi-disqus-com"
paginate = 5

[author]
    name = "robert choi"
    email = "robert@knlabs.kr"

[params]
    description = "KNLabs 오픈연구소 홈페이지입니다."



